const COLORS = [
  'IndianRed',
  'LightCoral',
  'Salmon',
  'DarkSalmon',
  'Crimson',
  'Red',
  'FireBrick',
  'Pink',
  'HotPink',
  'DeepPink',
  'Coral',
  'Tomato',
  'OrangeRed',
  'DarkOrange',
  'Orange',
  'Gold',
  'Khaki',
  'DarkKhaki',
  'Lavender',
  'Thistle',
  'Plum',
  'Violet',
  'Orchid',
  'Fuchsia',
  'Magenta',
  'MediumOrchid',
  'BlueViolet',
  'DarkViolet',
  'DarkOrchid',
  'SlateBlue',
  'GreenYellow',
  'Chartreuse',
  'LawnGreen',
  'Lime',
  'LimeGreen',
  'PaleGreen',
  'LightGreen',
  'SpringGreen',
  'SeaGreen',
  'YellowGreen',
  'DarkSeaGreen',
  'Aqua',
  'Cyan',
  'Aquamarine',
  'Turquoise',
  'CadetBlue',
  'SteelBlue',
  'PowderBlue',
  'SkyBlue',
  'LightBlue',
  'DeepSkyBlue',
  'DodgerBlue',
  'RoyalBlue',
  'MediumBlue',
  'Cornsilk',
  'Bisque',
  'NavajoWhite',
  'Wheat',
  'BurlyWood',
  'Tan',
  'RosyBrown',
  'SandyBrown',
  'Goldenrod',
  'Peru',
  'Chocolate',
  'Sienna',
  'Gainsboro',
  'LightGray',
  'Silver',
  'DarkGray',
  'Gray',
  'DimGray',
  'SlateGray',
];

const NAMES = [
  'Beppe',
  'Blanca',
  'Blathers',
  'Booker',
  'Brewster',
  'C.J.',
  'Carlo',
  'Celeste',
  'Chip',
  'Copper',
  'Cornimer',
  'Cyrus',
  'Daisy Mae',
  'Digby',
  'DJ KK',
  'Don Resetti',
  'Farley',
  'Flick',
  'Franklin',
  'Frillard',
  'Giovanni',
  'Gracie',
  'Grams',
  'Gullivarrr',
  'Gulliver',
  'Harriet',
  'Harvey',
  'Isabelle',
  'Jack',
  'Jingle',
  'Joan',
  'K.K. Slider',
  'Kaitlin',
  "Kapp'n",
  'Katie',
  'Katrina',
  'Kicks',
  'Label',
  'Leif',
  'Leila',
  'Leilani',
  'Lloid',
  'Lottie',
  'Luna',
  'Lyle',
  'Mabel',
  'Nat',
  'Niko',
  'Orville',
  'Parents',
  'Pascal',
  'Pavé',
  'Pelly',
  'Pete',
  'Phineas',
  'Phyllis',
  'Player',
  'Porter',
  'Redd',
  'Reese',
  'Mr. Resetti',
  'Rover',
  'Sable',
  'Saharah',
  'Serena',
  'Dr. Shrunk',
  'Snowboy',
  'Snowmam',
  'Snowman',
  'Snowtyke',
  'Somebody',
  'Special character',
  'Timmy and Tommy',
  'Tom Nook',
  'Tortimer',
  'Wardell',
  'Wendell',
  'Wilbur',
  'Wisp',
  'Xsq',
  'Zipper T. Bunny',
];

const FALLBACK_IMAGES = [
  {
    alias: 'Rover',
    img_url: 'https://dodo.ac/np/images/thumb/2/2e/Rover_NH_Character_Icon.png/100px-Rover_NH_Character_Icon.png',
  },
  {
    alias: 'Nookling',
    img_url: 'https://dodo.ac/np/images/thumb/3/36/Nookling_NH_Character_Icon.png/100px-Nookling_NH_Character_Icon.png',
  },
  {
    alias: 'Lyle',
    img_url: 'https://dodo.ac/np/images/thumb/8/81/Lyle_NH_Character_Icon.png/100px-Lyle_NH_Character_Icon.png',
  },
  {
    alias: 'Label',
    img_url: 'https://dodo.ac/np/images/thumb/c/c6/Label_NH_Character_Icon.png/100px-Label_NH_Character_Icon.png',
  },
  {
    alias: 'Jingle',
    img_url: 'https://dodo.ac/np/images/thumb/b/b1/Jingle_NH_Character_Icon.png/100px-Jingle_NH_Character_Icon.png',
  },
  {
    alias: 'Nookling',
    img_url: 'https://dodo.ac/np/images/thumb/3/36/Nookling_NH_Character_Icon.png/100px-Nookling_NH_Character_Icon.png',
  },
  {
    alias: 'Redd',
    img_url: 'https://dodo.ac/np/images/thumb/4/40/Redd_NH_Character_Icon.png/100px-Redd_NH_Character_Icon.png',
  },
];

async function hashValue(value) {
  const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value));
  return Array.from(new Uint8Array(bytes));
}

export async function getVisitorIdentity(visitorKey) {
  const bytes = await hashValue(visitorKey || crypto.randomUUID());
  const color = COLORS[(bytes[0] * 256 + bytes[1]) % COLORS.length];
  const name = NAMES[(bytes[2] * 256 + bytes[3]) % NAMES.length];
  const image = FALLBACK_IMAGES[(bytes[4] * 256 + bytes[5]) % FALLBACK_IMAGES.length];
  return { alias: name, color, img_url: image.img_url };
}
